version: "3.8"

services:
  app:
    platform: linux/amd64
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/srv/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
